[package]
name = "magichawk"
version = "0.1.0"
authors = ["Mathias Ritzmann <rimathia@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.6"
lazy_static = "1.4"
regex = "1"
rocket = "0.4.5"
base64 = "0.12.3"
rand = "0.7.3"
tiff = "0.5.0"
zip = "0.5.0"
fern = "0.6"
log = "0.4"
chrono = "0.4"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["serve"]

[dependencies.reqwest]
version = "0.10.6"
features = ["blocking"]