# Instruction + template repo: https://github.com/FedericoPonzi/rust-ci
name: release

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

  deploy:
    name: deploy
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/magichawk
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../magichawk-${{ matrix.target }}.tar.gz magichawk
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'magichawk*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
